### ISSUE TITLE
Calculation of Battery Power

### ISSUE THREAD

**Issue by audioheaven** [IPSCoyote/RCT-Power#1]
Hello,

In the calculation of the capacity is a mistake, because it takes the battery capacity from the PV power, but this does not have to be the PV capacity the same as the battery capacity.

**Comment by IPSCoyote** [comment]
Can you be more precise here? I guess you're talking about the AnalyzeResponse, but which case-branch (address) ?

**Comment by IPSCoyote** [comment]
This will be corrected in Version 1.0
