### ISSUE TITLE
Frage zur Dokumenation

### ISSUE THREAD

**Issue by waigel** [IPSCoyote/RCT-Power#4]
Hallo,

du schreibst öfter in deinem Code von einer Dokumentation.
Hast du dafür einen Link oder eine passende PDF?

Viele Grüße
Johannes

**Comment by IPSCoyote** [comment]
Ich habe eine Dokumentation von RCT-Power direkt. Ggf. dort mal direkt anfragen. Ich möchte sie nicht zu viel rumschicken.
