### ISSUE TITLE
Received data

### ISSUE THREAD

**Issue by Termits13** [IPSCoyote/RCT-Power#5]
hello, i unable received data without running app on phone. When app on phone running data in symcon updates.

**Comment by IPSCoyote** [comment]
Do you've setup an update interval win the setup of the Instance?

The module reacts on every communication on the TCP connection, So if the mobile requests data, my module also logs the data. Without an update interval, my module is not requesting the data by itself. I request data every 15 seconds.

**Comment by IPSCoyote** [comment]
New Version 1.0 released
