### ISSUE TITLE
To C#

### ISSUE THREAD

**Issue by michalss** [IPSCoyote/RCT-Power#8]
Hi, i have a small question about this module as im looking for working api for DC6.0 as i would like to make some control application and most likely some kind of reporting system for this. is this can read also historical data from DC? Is there any chance to convert it to C# class pls ?

**Comment by cattitude** [comment]
Hi, I don't wanna make separate issue just for this question, since it is not really an issue. Unfortunately this the only way to contact you. I've found this repository a couple of months ago and I've been able to make a small home control system based on information provided by DC 6.0. Is there any official documentation from RCT Power regarding the API or have you figured out it by yourself? Thanks!

**Comment by michalss** [comment]
Can you please share it for us? BTW if you decompile apk from android there is many result codes and exact meaning for them.

**Comment by cattitude** [comment]
> Can you please share it for us? BTW if you decompile apk from android there is many result codes and exact meaning for them.

Thanks! That's exactly, what I needed to know. Also there is really nothing to share, my control system was just modified code from this repository and a couple of if clauses to turn on/off heating based on current amount of power going to grid.

**Comment by michalss** [comment]
My issue is php, i would prefere more solid solution like c# or c++ classes.. :( to bad this is php..

**Comment by michalss** [comment]
but still, did you use this php code or did u convert it to c# class ?

**Comment by cattitude** [comment]
I've used this php code, but I've used it mainly for testing purposes, it's not something I run 24/7. If you already know C#, it shouldn't be a problem to learn some basics of php and rewrite it.

**Comment by michalss** [comment]
OK anyways, can you please at least share with me usage of this module ? For example how to read something, anything from DC6 ? I know php a bit, but this looks a too complicated to figure out the usage for me.. Thx

**Comment by cattitude** [comment]
Yeah, sure. How can I contact you?

**Comment by michalss** [comment]
> Yeah, sure. How can I contact you?

please just on email : multileech@gmail.com. Please tell me when i can delete it from here.. Thx

**Comment by cattitude** [comment]
You can.

**Comment by michalss** [comment]
ok thx for help, will see i can do about this :)

**Comment by michalss** [comment]
ok sorted thank a lot @cattitude

**Comment by hanzsez** [comment]
@michalss or @cattitude can you please shre your repos, or at least information how and where you modified the existing php to poll test data ?

**Comment by cattitude** [comment]
[rct.zip](https://github.com/IPSCoyote/RCT-Power/files/5408486/rct.zip)
It is suitable only for testing and inspiration! The code isn't very nice, contains global variables, but I think it should help you understand, how it works. To run this script, you need to modify IP addresses in socket_bind and socket_connect functions, see comments in the code for more info. Then simply run the script in terminal/console and you should be able to see data from your inverter. If you have any questions, feel free to contact me via email displayed on my github profile ;)
